In [3]:
import pandas as pd
import numpy as np
rack = np.ones((4,4))
servo1 = 0 
servo2 = 0
servo3 = 0
servo4 = 0
servo5 = 0
print(rack)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:

bandera = 0
column = 0
entrada = input('Ingrese el nombre del medicamento que busca')
if entrada == 'Medicamento 1':
    column = 0;
elif entrada == 'Medicamento 2':
    column = 1;
elif entrada == 'Medicamento 3':
    column = 2;
elif entrada == 'Medicamento 4':
    column = 3;
else:
    column = 5
    
try:
    for i in range(len(rack)):
        if rack[i,column] == 1 and bandera == 0:
            print('Medicamento encontrado en posicion {},{}'.format(i,column))
            bandera = 1
except:
    print('Medicamento no encontrado en el rack')

Ingrese el nombre del medicamento que buscaMedicamento 1
Medicamento encontrado en posicion 0,0


<class 'int'>


Medicamento encontrado en posicion 1,1
